name: Excavator
on:
  workflow_dispatch:
  schedule:
    - cron: '20 */4 * * *'  # Every 4 hours (matches official template)
permissions:
  contents: read
jobs:
  excavate:
    name: Excavate
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Excavate
        uses: ScoopInstaller/GithubActions@7cba138914e4a9feca3c7b5461d87ef466a5c458 # main as of 2026-08-24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
